### ISSUE TITLE
Saving screenshot Selenium 4.16+

### ISSUE THREAD

**Issue by DanMcNamee42** [OpenMAQS/openmaqs-dotnet#167]
We tried updating Selenium to version 4.16.2 and when a test would error we no longer get a screenshot of the error.  The log displays the following message:

WARNING:	Failed to get screen shot because: Could not load type 'OpenQA.Selenium.ScreenshotImageFormat' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.

It appears that Selenium has deprecated ScreenshotImageFormat, so for saving screenshot images, the SaveAsFile(string fileName, ScreenshotImageFormat format) method no longer works.  Images will only save to png format and use the SaveAdFile(string fileName) method to save.

[https://www.selenium.dev/selenium/docs/api/dotnet/OpenQA.Selenium.Screenshot.html](https://www.selenium.dev/selenium/docs/api/dotnet/OpenQA.Selenium.Screenshot.html)

**Comment by jonreding2010** [comment]
> We tried updating Selenium to version 4.16.2 and when a test would error we no longer get a screenshot of the error. The log displays the following message:
> 
> WARNING: Failed to get screen shot because: Could not load type 'OpenQA.Selenium.ScreenshotImageFormat' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> It appears that Selenium has deprecated ScreenshotImageFormat, so for saving screenshot images, the SaveAsFile(string fileName, ScreenshotImageFormat format) method no longer works. Images will only save to png format and use the SaveAdFile(string fileName) method to save.
> 
> https://www.selenium.dev/selenium/docs/api/dotnet/OpenQA.Selenium.Screenshot.html

We have this PR: https://github.com/OpenMAQS/openmaqs-dotnet/pull/156 that takes the deprecation of ScreenshotImageFormat into account. Hoping to have it reviewed and merged soon

**Comment by DanMcNamee42** [comment]
> We have this PR: #156 that takes the deprecation of ScreenshotImageFormat into account. Hoping to have it reviewed and merged soon

I see you have closed the PR.  Any idea when the next release will be coming that includes the fix?  We are planning to migrate from CognizantMAQS to OpenMAQS on April 5th, and it would be really nice to have this.

**Comment by TroyWalshProf** [comment]
Will take silence as affirmation.
Closing.
If this is still an issue, please feel free to reopen.
