### ISSUE TITLE
Update MAQS Appium support

### ISSUE THREAD

**Issue by DanMcNamee42** [OpenMAQS/openmaqs-dotnet#240]
Appium 2 has finally been released.  MAQS is currently using a beta Appium that is 7 releases behind the release and is not compatible with the current release of Appium Server.  For compatibility, support of new features and security we could use an Appium update in MAQS.

**Comment by TroyWalshProf** [comment]
Drat, I thought we updated to 5.0.0 with release 10.0.1.
Latest release [10.0.2](https://www.nuget.org/packages/OpenMAQS.Maqs.Appium/10.0.2#dependencies-body-tab) is updated to Appium 5.1.0.

**Comment by DanMcNamee42** [comment]
Hi Troy.  I haven't checked yet, but in the release notes email that went out last night, it showed Appium 5.0.0 was in the release instead of 5.1.0.  Unfortunately, there is a bug in 5.0.0 that makes it incompatible with newer versions of Selenium.  That is fixed in 5.1.0.

**Comment by DanMcNamee42** [comment]
I grabbed the code and checked it, and it is Appium 5.1.0, so that's all good.
