### ISSUE TITLE
Update MSTest to v3

### ISSUE THREAD

**Issue by jonreding2010** [OpenMAQS/openmaqs-dotnet#84]
[[A version 3 of MSTest and its related packages (MSTest.Framework and MSTest.TestAdapter) ](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md)have been released.](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md) MAQS is currently in use at RSM for test automation, and they would like to take advantage of features in version 3.

[I tried just updating the packages in a branch off of main](https://github.com/brannen-hall-csv/maqs-dotnet/commit/354664c4b43be86483687e23338f3dd3a1b6af3b), and it looks like there already are some breaking changes to Assert.AreNotEqual and Assert.AreEqual when comparing two Object instances that folks will have to be aware of when upgrading.

Is it possible for this to make it into the next release? Are there any other obstacles to upgrading MSTest to v3?

original issue can be found here: https://github.com/CognizantOpenSource/maqs-dotnet/issues

**Comment by DanMcNamee42** [comment]
Might run into problems with .Net versions being too old for the latest version of MSTest.Framework and MSTest.TestAdapter.

I have updated the entire project locally to .Net 6 and have not seen any issues other that during the update in the MoqMailFolder unit tests there were two new interfaces for IMailFolder that were not implemented.

I have also updated all packages to current, and a few unit tests need to be repaired.  Updating MSTest.Framework and MSTest.TestAdapter causes 4 unit tests to break.  Everything in MAQS itself appears to be fine, just a few unit tests need repair after updating everything.

**Comment by jonreding2010** [comment]
> Might run into problems with .Net versions being too old for the latest version of MSTest.Framework and MSTest.TestAdapter.
> 
> I have updated the entire project locally to .Net 6 and have not seen any issues other that during the update in the MoqMailFolder unit tests there were two new interfaces for IMailFolder that were not implemented.
> 
> I have also updated all packages to current, and a few unit tests need to be repaired. Updating MSTest.Framework and MSTest.TestAdapter causes 4 unit tests to break. Everything in MAQS itself appears to be fine, just a few unit tests need repair after updating everything.

Thanks for that, we'll look into it.
We are in the process of stabilizing MAQS C#, stay tuned as we should have the repo running soon

**Comment by DanMcNamee42** [comment]
Thank you!  You guys had a busy weekend.  Looking great!
