### ISSUE TITLE
Replace Troy's Axe Nuget Reference with Deque

### ISSUE THREAD

**Issue by jonreding2010** [OpenMAQS/openmaqs-dotnet#89]
Change nutget reference of Troy's repo to dequelabs.

The NuGet package will be deprecated and a new repo will be set as the alternate package

The new Deque project will support both Selenium and Playwright
A new project (https://github.com/microsoft/html-reporter-for-axe-core-dotnet) will be used for creating HTML reports. This should provide a much better user experience than the admittedly primitive reporting currently included in Selenium.Axe

**Comment by TroyWalshProf** [comment]
@jonreding2010 - Checking with the the reporting team to see if we can get an eta
https://github.com/microsoft/html-reporter-for-axe-core-dotnet/issues/46

**Comment by TroyWalshProf** [comment]
@jonreding2010 - The MS HTML report is taking too long
I created this as a stopgap - https://www.nuget.org/packages/TWP.Selenium.Axe.Html/

**Comment by jonreding2010** [comment]
> @jonreding2010 - The MS HTML report is taking too long I created this as a stopgap - https://www.nuget.org/packages/TWP.Selenium.Axe.Html/
Sounds good! I made this issue as a reminder/placeholder for the update to the Microsoft axe reporter.

You stopgap sounds good to me

**Comment by TroyWalshProf** [comment]
Done in[ last release](https://github.com/OpenMAQS/openmaqs-dotnet/releases/tag/v10.0.1)
